SENHASEGURA_URL: "https://10.0.0.161"
SENHASEGURA_CLIENT_ID: "e1df7181e62322cd79b7031acd2dc9f0061fab085"
SENHASEGURA_CLIENT_SECRET: "b4f93a894baf31a9323a6be2082f7fa0"
SENHASEGURA_MAPPING_FILE: ".mapping.json"
SENHASEGURA_SECRETS_FOLDER: "/home/admin/secrets/"
